[package]
name = "day-01"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "day-01"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

